import akshare as ak
from typing import Dict, Any
from lib.logger import logger
from lib.tools.cache_decorator import use_cache
from lib.utils.symbol import determine_exchange
from .utils import colum_mapping_transform

@use_cache(86400 * 7, use_db_cache=True)
def get_financial_cash_flow_history(symbol: str) -> Dict[str, Any]:
    """
    获取A股公司现金流量表历史数据

    Args:
        symbol: 股票代码

    Returns:
        包含现金流量表历史数据的字典
    """
    result = {
        "symbol": symbol,
        "source": "新浪财经-财务分析-现金流量表",
        "data": [],
    }
    try:
        df = ak.stock_financial_report_sina(stock=symbol, symbol="现金流量表")
        for _, row in df.iterrows():
            result["data"].append(row.dropna().to_dict())
        if result["data"]:
            return result
    except Exception as e:
        logger.error("获取现金流量表历史数据失败: %s, 尝试切换到其他数据源", e)
    
    CASH_FLOW_COLUMN_MAP = {
        "SECUCODE": "证券代码",
        "SECURITY_CODE": "股票代码",
        "SECURITY_NAME_ABBR": "股票简称",
        "ORG_CODE": "机构代码",
        "ORG_TYPE": "机构类型",
        "REPORT_DATE": "报告日",
        "REPORT_TYPE": "报告类型",
        "REPORT_DATE_NAME": "报告期",
        "SECURITY_TYPE_CODE": "证券类型代码",
        "NOTICE_DATE": "公告日期",
        "UPDATE_DATE": "更新日期",
        "CURRENCY": "币种",
        "SALES_SERVICES": "销售商品、提供劳务收到的现金",
        "DEPOSIT_INTERBANK_ADD": "客户存款和同业存放款项净增加额",
        "LOAN_PBC_ADD": "向中央银行借款净增加额",
        "OFI_BF_ADD": "向其他金融机构拆入资金净增加额",
        "RECEIVE_ORIGIC_PREMIUM": "收到原保险合同保费取得的现金",
        "RECEIVE_REINSURE_NET": "收到再保险业务现金净额",
        "INSURED_INVEST_ADD": "保户储金及投资款净增加额",
        "DISPOSAL_TFA_ADD": "处置交易性金融资产净增加额",
        "RECEIVE_INTEREST_COMMISSION": "收取利息、手续费及佣金的现金",
        "BORROW_FUND_ADD": "拆入资金净增加额",
        "LOAN_ADVANCE_REDUCE": "客户贷款及垫款净增加额",
        "REPO_BUSINESS_ADD": "回购业务资金净增加额",
        "RECEIVE_TAX_REFUND": "收到的税费返还",
        "RECEIVE_OTHER_OPERATE": "收到的其他与经营活动有关的现金",
        "OPERATE_INFLOW_OTHER": "经营活动现金流入其他",
        "OPERATE_INFLOW_BALANCE": "经营活动现金流入小计",
        "TOTAL_OPERATE_INFLOW": "经营活动现金流入合计",
        "BUY_SERVICES": "购买商品、接受劳务支付的现金",
        "LOAN_ADVANCE_ADD": "客户贷款及垫款净增加额",
        "PBC_INTERBANK_ADD": "存放中央银行和同业款项净增加额",
        "PAY_ORIGIC_COMPENSATE": "支付原保险合同赔付款项的现金",
        "PAY_INTEREST_COMMISSION": "支付利息、手续费及佣金的现金",
        "PAY_POLICY_BONUS": "支付保单红利的现金",
        "PAY_STAFF_CASH": "支付给职工以及为职工支付的现金",
        "PAY_ALL_TAX": "支付的各项税费",
        "PAY_OTHER_OPERATE": "支付的其他与经营活动有关的现金",
        "OPERATE_OUTFLOW_OTHER": "经营活动现金流出其他",
        "OPERATE_OUTFLOW_BALANCE": "经营活动现金流出小计",
        "TOTAL_OPERATE_OUTFLOW": "经营活动现金流出合计",
        "OPERATE_NETCASH_OTHER": "经营活动产生的现金流量净额其他",
        "OPERATE_NETCASH_BALANCE": "经营活动产生的现金流量净额小计",
        "NETCASH_OPERATE": "经营活动产生的现金流量净额",
        "WITHDRAW_INVEST": "收回投资所收到的现金",
        "RECEIVE_INVEST_INCOME": "取得投资收益收到的现金",
        "DISPOSAL_LONG_ASSET": "处置固定资产、无形资产和其他长期资产所收回的现金净额",
        "DISPOSAL_SUBSIDIARY_OTHER": "处置子公司及其他营业单位收到的现金净额",
        "REDUCE_PLEDGE_TIMEDEPOSITS": "减少质押和定期存款所收到的现金",
        "RECEIVE_OTHER_INVEST": "收到的其他与投资活动有关的现金",
        "INVEST_INFLOW_OTHER": "投资活动现金流入其他",
        "INVEST_INFLOW_BALANCE": "投资活动现金流入小计",
        "TOTAL_INVEST_INFLOW": "投资活动现金流入合计",
        "CONSTRUCT_LONG_ASSET": "购建固定资产、无形资产和其他长期资产所支付的现金",
        "INVEST_PAY_CASH": "投资所支付的现金",
        "PLEDGE_LOAN_ADD": "质押贷款净增加额",
        "OBTAIN_SUBSIDIARY_OTHER": "取得子公司及其他营业单位支付的现金净额",
        "ADD_PLEDGE_TIMEDEPOSITS": "增加质押和定期存款所支付的现金",
        "PAY_OTHER_INVEST": "支付的其他与投资活动有关的现金",
        "INVEST_OUTFLOW_OTHER": "投资活动现金流出其他",
        "INVEST_OUTFLOW_BALANCE": "投资活动现金流出小计",
        "TOTAL_INVEST_OUTFLOW": "投资活动现金流出合计",
        "INVEST_NETCASH_OTHER": "投资活动产生的现金流量净额其他",
        "INVEST_NETCASH_BALANCE": "投资活动产生的现金流量净额小计",
        "NETCASH_INVEST": "投资活动产生的现金流量净额",
        "ACCEPT_INVEST_CASH": "吸收投资收到的现金",
        "SUBSIDIARY_ACCEPT_INVEST": "子公司吸收少数股东投资收到的现金",
        "RECEIVE_LOAN_CASH": "取得借款收到的现金",
        "ISSUE_BOND": "发行债券收到的现金",
        "RECEIVE_OTHER_FINANCE": "收到其他与筹资活动有关的现金",
        "FINANCE_INFLOW_OTHER": "筹资活动现金流入其他",
        "FINANCE_INFLOW_BALANCE": "筹资活动现金流入小计",
        "TOTAL_FINANCE_INFLOW": "筹资活动现金流入合计",
        "PAY_DEBT_CASH": "偿还债务支付的现金",
        "ASSIGN_DIVIDEND_PORFIT": "分配股利、利润或偿付利息所支付的现金",
        "SUBSIDIARY_PAY_DIVIDEND": "子公司支付给少数股东的股利、利润",
        "BUY_SUBSIDIARY_EQUITY": "购买子公司股权支付的现金",
        "PAY_OTHER_FINANCE": "支付其他与筹资活动有关的现金",
        "SUBSIDIARY_REDUCE_CASH": "子公司减少现金",
        "FINANCE_OUTFLOW_OTHER": "筹资活动现金流出其他",
        "FINANCE_OUTFLOW_BALANCE": "筹资活动现金流出小计",
        "TOTAL_FINANCE_OUTFLOW": "筹资活动现金流出合计",
        "FINANCE_NETCASH_OTHER": "筹资活动产生的现金流量净额其他",
        "FINANCE_NETCASH_BALANCE": "筹资活动产生的现金流量净额小计",
        "NETCASH_FINANCE": "筹资活动产生的现金流量净额",
        "RATE_CHANGE_EFFECT": "汇率变动对现金及现金等价物的影响",
        "CCE_ADD_OTHER": "现金及现金等价物净增加额其他",
        "CCE_ADD_BALANCE": "现金及现金等价物净增加额小计",
        "CCE_ADD": "现金及现金等价物净增加额",
        "BEGIN_CCE": "期初现金及现金等价物余额",
        "END_CCE_OTHER": "期末现金及现金等价物余额其他",
        "END_CCE_BALANCE": "期末现金及现金等价物余额小计",
        "END_CCE": "期末现金及现金等价物余额",
        "NETPROFIT": "净利润",
        "ASSET_IMPAIRMENT": "资产减值损失",
        "FA_IR_DEPR": "固定资产折旧",
        "OILGAS_BIOLOGY_DEPR": "油气及生物资产折旧",
        "IR_DEPR": "无形资产摊销",
        "IA_AMORTIZE": "无形资产摊销",
        "LPE_AMORTIZE": "长期待摊费用摊销",
        "DEFER_INCOME_AMORTIZE": "递延收益摊销",
        "PREPAID_EXPENSE_REDUCE": "预付费用减少",
        "ACCRUED_EXPENSE_ADD": "应计费用增加",
        "DISPOSAL_LONGASSET_LOSS": "处置长期资产损失",
        "FA_SCRAP_LOSS": "固定资产报废损失",
        "FAIRVALUE_CHANGE_LOSS": "公允价值变动损失",
        "FINANCE_EXPENSE": "财务费用",
        "INVEST_LOSS": "投资损失",
        "DEFER_TAX": "递延所得税",
        "DT_ASSET_REDUCE": "递延所得税资产减少",
        "DT_LIAB_ADD": "递延所得税负债增加",
        "PREDICT_LIAB_ADD": "预计负债增加",
        "INVENTORY_REDUCE": "存货减少",
        "OPERATE_RECE_REDUCE": "经营性应收项目减少",
        "OPERATE_PAYABLE_ADD": "经营性应付项目增加",
        "OTHER": "其他",
        "OPERATE_NETCASH_OTHERNOTE": "经营活动产生的现金流量净额其他说明",
        "OPERATE_NETCASH_BALANCENOTE": "经营活动产生的现金流量净额小计说明",
        "NETCASH_OPERATENOTE": "经营活动产生的现金流量净额说明",
        "DEBT_TRANSFER_CAPITAL": "债务转为资本",
        "CONVERT_BOND_1YEAR": "一年内到期可转换公司债券",
        "FINLEASE_OBTAIN_FA": "融资租赁取得固定资产",
        "UNINVOLVE_INVESTFIN_OTHER": "未涉及投资和筹资活动的其他事项",
        "END_CASH": "期末现金余额",
        "BEGIN_CASH": "期初现金余额",
        "OPINION_TYPE": "审计意见类型",
        "OSOPINION_TYPE": "原审计意见类型",
        "MINORITY_INTEREST": "少数股东权益",
        "USERIGHT_ASSET_AMORTIZE": "使用权资产摊销",
        "END_CASH_EQUIVALENTS": "期末现金及现金等价物余额",
        "BEGIN_CASH_EQUIVALENTS": "期初现金及现金等价物余额",
        "CCE_ADD_OTHERNOTE": "现金及现金等价物净增加额其他说明",
        "CCE_ADD_BALANCENOTE": "现金及现金等价物净增加额小计说明",
        "CCE_ADDNOTE": "现金及现金等价物净增加额说明",
        "SALES_SERVICES_YOY": "销售商品、提供劳务收到的现金同比",
        "DEPOSIT_INTERBANK_ADD_YOY": "客户存款和同业存放款项净增加额同比",
        "LOAN_PBC_ADD_YOY": "向中央银行借款净增加额同比",
        "OFI_BF_ADD_YOY": "向其他金融机构拆入资金净增加额同比",
        "RECEIVE_ORIGIC_PREMIUM_YOY": "收到原保险合同保费取得的现金同比",
        "RECEIVE_REINSURE_NET_YOY": "收到再保险业务现金净额同比",
        "INSURED_INVEST_ADD_YOY": "保户储金及投资款净增加额同比",
        "DISPOSAL_TFA_ADD_YOY": "处置交易性金融资产净增加额同比",
        "RECEIVE_INTEREST_COMMISSION_YOY": "收取利息、手续费及佣金的现金同比",
        "BORROW_FUND_ADD_YOY": "拆入资金净增加额同比",
        "LOAN_ADVANCE_REDUCE_YOY": "客户贷款及垫款净增加额同比",
        "REPO_BUSINESS_ADD_YOY": "回购业务资金净增加额同比",
        "RECEIVE_TAX_REFUND_YOY": "收到的税费返还同比",
        "RECEIVE_OTHER_OPERATE_YOY": "收到的其他与经营活动有关的现金同比",
        "OPERATE_INFLOW_OTHER_YOY": "经营活动现金流入其他同比",
        "OPERATE_INFLOW_BALANCE_YOY": "经营活动现金流入小计同比",
        "TOTAL_OPERATE_INFLOW_YOY": "经营活动现金流入合计同比",
        "BUY_SERVICES_YOY": "购买商品、接受劳务支付的现金同比",
        "LOAN_ADVANCE_ADD_YOY": "客户贷款及垫款净增加额同比",
        "PBC_INTERBANK_ADD_YOY": "存放中央银行和同业款项净增加额同比",
        "PAY_ORIGIC_COMPENSATE_YOY": "支付原保险合同赔付款项的现金同比",
        "PAY_INTEREST_COMMISSION_YOY": "支付利息、手续费及佣金的现金同比",
        "PAY_POLICY_BONUS_YOY": "支付保单红利的现金同比",
        "PAY_STAFF_CASH_YOY": "支付给职工以及为职工支付的现金同比",
        "PAY_ALL_TAX_YOY": "支付的各项税费同比",
        "PAY_OTHER_OPERATE_YOY": "支付的其他与经营活动有关的现金同比",
        "OPERATE_OUTFLOW_OTHER_YOY": "经营活动现金流出其他同比",
        "OPERATE_OUTFLOW_BALANCE_YOY": "经营活动现金流出小计同比",
        "TOTAL_OPERATE_OUTFLOW_YOY": "经营活动现金流出合计同比",
        "OPERATE_NETCASH_OTHER_YOY": "经营活动产生的现金流量净额其他同比",
        "OPERATE_NETCASH_BALANCE_YOY": "经营活动产生的现金流量净额小计同比",
        "NETCASH_OPERATE_YOY": "经营活动产生的现金流量净额同比",
        "WITHDRAW_INVEST_YOY": "收回投资所收到的现金同比",
        "RECEIVE_INVEST_INCOME_YOY": "取得投资收益收到的现金同比",
        "DISPOSAL_LONG_ASSET_YOY": "处置固定资产、无形资产和其他长期资产所收回的现金净额同比",
        "DISPOSAL_SUBSIDIARY_OTHER_YOY": "处置子公司及其他营业单位收到的现金净额同比",
        "REDUCE_PLEDGE_TIMEDEPOSITS_YOY": "减少质押和定期存款所收到的现金同比",
        "RECEIVE_OTHER_INVEST_YOY": "收到的其他与投资活动有关的现金同比",
        "INVEST_INFLOW_OTHER_YOY": "投资活动现金流入其他同比",
        "INVEST_INFLOW_BALANCE_YOY": "投资活动现金流入小计同比",
        "TOTAL_INVEST_INFLOW_YOY": "投资活动现金流入合计同比",
        "CONSTRUCT_LONG_ASSET_YOY": "购建固定资产、无形资产和其他长期资产所支付的现金同比",
        "INVEST_PAY_CASH_YOY": "投资所支付的现金同比",
        "PLEDGE_LOAN_ADD_YOY": "质押贷款净增加额同比",
        "OBTAIN_SUBSIDIARY_OTHER_YOY": "取得子公司及其他营业单位支付的现金净额同比",
        "ADD_PLEDGE_TIMEDEPOSITS_YOY": "增加质押和定期存款所支付的现金同比",
        "PAY_OTHER_INVEST_YOY": "支付的其他与投资活动有关的现金同比",
        "INVEST_OUTFLOW_OTHER_YOY": "投资活动现金流出其他同比",
        "INVEST_OUTFLOW_BALANCE_YOY": "投资活动现金流出小计同比",
        "TOTAL_INVEST_OUTFLOW_YOY": "投资活动现金流出合计同比",
        "INVEST_NETCASH_OTHER_YOY": "投资活动产生的现金流量净额其他同比",
        "INVEST_NETCASH_BALANCE_YOY": "投资活动产生的现金流量净额小计同比",
        "NETCASH_INVEST_YOY": "投资活动产生的现金流量净额同比",
        "ACCEPT_INVEST_CASH_YOY": "吸收投资收到的现金同比",
        "SUBSIDIARY_ACCEPT_INVEST_YOY": "子公司吸收少数股东投资收到的现金同比",
        "RECEIVE_LOAN_CASH_YOY": "取得借款收到的现金同比",
        "ISSUE_BOND_YOY": "发行债券收到的现金同比",
        "RECEIVE_OTHER_FINANCE_YOY": "收到其他与筹资活动有关的现金同比",
        "FINANCE_INFLOW_OTHER_YOY": "筹资活动现金流入其他同比",
        "FINANCE_INFLOW_BALANCE_YOY": "筹资活动现金流入小计同比",
        "TOTAL_FINANCE_INFLOW_YOY": "筹资活动现金流入合计同比",
        "PAY_DEBT_CASH_YOY": "偿还债务支付的现金同比",
        "ASSIGN_DIVIDEND_PORFIT_YOY": "分配股利、利润或偿付利息所支付的现金同比",
        "SUBSIDIARY_PAY_DIVIDEND_YOY": "子公司支付给少数股东的股利、利润同比",
        "BUY_SUBSIDIARY_EQUITY_YOY": "购买子公司股权支付的现金同比",
        "PAY_OTHER_FINANCE_YOY": "支付其他与筹资活动有关的现金同比",
        "SUBSIDIARY_REDUCE_CASH_YOY": "子公司减少现金同比",
        "FINANCE_OUTFLOW_OTHER_YOY": "筹资活动现金流出其他同比",
        "FINANCE_OUTFLOW_BALANCE_YOY": "筹资活动现金流出小计同比",
        "TOTAL_FINANCE_OUTFLOW_YOY": "筹资活动现金流出合计同比",
        "FINANCE_NETCASH_OTHER_YOY": "筹资活动产生的现金流量净额其他同比",
        "FINANCE_NETCASH_BALANCE_YOY": "筹资活动产生的现金流量净额小计同比",
        "NETCASH_FINANCE_YOY": "筹资活动产生的现金流量净额同比",
        "RATE_CHANGE_EFFECT_YOY": "汇率变动对现金及现金等价物的影响同比",
        "CCE_ADD_OTHER_YOY": "现金及现金等价物净增加额其他同比",
        "CCE_ADD_BALANCE_YOY": "现金及现金等价物净增加额小计同比",
        "CCE_ADD_YOY": "现金及现金等价物净增加额同比",
        "BEGIN_CCE_YOY": "期初现金及现金等价物余额同比",
        "END_CCE_OTHER_YOY": "期末现金及现金等价物余额其他同比",
        "END_CCE_BALANCE_YOY": "期末现金及现金等价物余额小计同比",
        "END_CCE_YOY": "期末现金及现金等价物余额同比",
        "NETPROFIT_YOY": "净利润同比",
        "ASSET_IMPAIRMENT_YOY": "资产减值损失同比",
        "FA_IR_DEPR_YOY": "固定资产折旧同比",
        "OILGAS_BIOLOGY_DEPR_YOY": "油气及生物资产折旧同比",
        "IR_DEPR_YOY": "无形资产摊销同比",
        "IA_AMORTIZE_YOY": "无形资产摊销同比",
        "LPE_AMORTIZE_YOY": "长期待摊费用摊销同比",
        "DEFER_INCOME_AMORTIZE_YOY": "递延收益摊销同比",
        "PREPAID_EXPENSE_REDUCE_YOY": "预付费用减少同比",
        "ACCRUED_EXPENSE_ADD_YOY": "应计费用增加同比",
        "DISPOSAL_LONGASSET_LOSS_YOY": "处置长期资产损失同比",
        "FA_SCRAP_LOSS_YOY": "固定资产报废损失同比",
        "FAIRVALUE_CHANGE_LOSS_YOY": "公允价值变动损失同比",
        "FINANCE_EXPENSE_YOY": "财务费用同比",
        "INVEST_LOSS_YOY": "投资损失同比",
        "DEFER_TAX_YOY": "递延所得税同比",
        "DT_ASSET_REDUCE_YOY": "递延所得税资产减少同比",
        "DT_LIAB_ADD_YOY": "递延所得税负债增加同比",
        "PREDICT_LIAB_ADD_YOY": "预计负债增加同比",
        "INVENTORY_REDUCE_YOY": "存货减少同比",
        "OPERATE_RECE_REDUCE_YOY": "经营性应收项目减少同比",
        "OPERATE_PAYABLE_ADD_YOY": "经营性应付项目增加同比",
        "OTHER_YOY": "其他同比",
        "OPERATE_NETCASH_OTHERNOTE_YOY": "经营活动产生的现金流量净额其他说明同比",
        "OPERATE_NETCASH_BALANCENOTE_YOY": "经营活动产生的现金流量净额小计说明同比",
        "NETCASH_OPERATENOTE_YOY": "经营活动产生的现金流量净额说明同比",
        "DEBT_TRANSFER_CAPITAL_YOY": "债务转为资本同比",
        "CONVERT_BOND_1YEAR_YOY": "一年内到期可转换公司债券同比",
        "FINLEASE_OBTAIN_FA_YOY": "融资租赁取得固定资产同比",
        "UNINVOLVE_INVESTFIN_OTHER_YOY": "未涉及投资和筹资活动的其他事项同比",
        "END_CASH_YOY": "期末现金余额同比",
        "BEGIN_CASH_YOY": "期初现金余额同比",
        "END_CASH_EQUIVALENTS_YOY": "期末现金及现金等价物余额同比",
        "BEGIN_CASH_EQUIVALENTS_YOY": "期初现金及现金等价物余额同比",
        "CCE_ADD_OTHERNOTE_YOY": "现金及现金等价物净增加额其他说明同比",
        "CCE_ADD_BALANCENOTE_YOY": "现金及现金等价物净增加额小计说明同比",
        "CCE_ADDNOTE_YOY": "现金及现金等价物净增加额说明同比",
        "MINORITY_INTEREST_YOY": "少数股东权益同比",
        "USERIGHT_ASSET_AMORTIZE_YOY": "使用权资产摊销同比",
    }
    df = ak.stock_cash_flow_sheet_by_report_em(symbol=determine_exchange(symbol) + symbol)
    result['source'] = "东方财富-股票-财务分析-现金流量表-按报告期"
    for _, row in df.iterrows():
        result["data"].append(colum_mapping_transform(row, CASH_FLOW_COLUMN_MAP))
    return result

def get_recent_financial_cash_flow(symbol: str) -> Dict[str, Any]:
    """
    获取A股公司现金流量表数据

    Args:
        symbol: 股票代码

    Returns:
        包含现金流量表数据的字典
    """
    result = get_financial_cash_flow_history(symbol).copy()
    result['data'] = result['data'][0] if result['data'] else {}
    return result
